### ISSUE TITLE
Image caption (nested editable) steals the selection

### ISSUE THREAD

**Issue by oskarwrobel** [ckeditor/ckeditor5-image#108]
I'm not able to select text fragment with an image.

![may-08-2017 11-58-39](https://cloud.githubusercontent.com/assets/1057056/25799572/c26feff4-33e5-11e7-92f7-d00445612704.gif)

**Comment by Reinmar** [comment]
I noticed this recently too.

But this is tricky. When selection starts outside a widget and you keep dragging it through a nested editable, the selection should either stop before the image or immediately contain the whole image. That's the ideal behaviour because the selection should never cross editable boundaries.

The okeysh behaviour would be if that was fixed after you release the mouse button. So, when dragging the selection may be incorrect, but it needs to be fixed after you finish making it.

**Comment by Reinmar** [comment]
Of course, right now the bug is that you may not be able to select e.g. entire editor content.

**Comment by oskarwrobel** [comment]
Works fine when selection starts on top of the image.

![may-08-2017 12-11-04](https://cloud.githubusercontent.com/assets/1057056/25800018/cff4acbc-33e7-11e7-9a92-dcccff1fb1d2.gif)

**Comment by oleq** [comment]
> or immediately contain the whole image. 

> That's the ideal behaviour because the selection should never cross editable boundaries.

Is it possible to implement it that way? Because to me, this is what makes sense in such situation.

**Comment by Reinmar** [comment]
> Is it possible to implement it that way? Because to me, this is what makes sense in such situation.

Yes and no. We can change the selection while the user is making it but if we'll be constantly fixing it when the user drags the mouse the selection will blink. @szymonkups was working on such a solution (we postponed the ticket because it wasn't trivial) and perhaps he can say something more.

**Comment by fredck** [comment]
> the selection should ... immediately contain the whole image

+1

**Comment by szymonkups** [comment]
I've made couple attempts to fix this issue on our side - which all resulted in some hacks that were causing other issues. I've [reported this issue to chromium bug tracker](https://bugs.chromium.org/p/chromium/issues/detail?id=782158&q=contenteditable%20selection&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified), let's wait for the answer.

**Comment by jodator** [comment]
@Reinmar This looks like fixed by https://github.com/ckeditor/ckeditor5-engine/pull/1431.
