### ISSUE TITLE
ContextualToolbar displays for the image caption

### ISSUE THREAD

**Issue by oskarwrobel** [ckeditor/ckeditor5-image#112]
Is it bug or feature? It works fine :) 

![may-10-2017 22-32-14](https://cloud.githubusercontent.com/assets/1057056/25919962/976e3634-35d0-11e7-896f-dc6e97e88c8a.gif)

**Comment by oskarwrobel** [comment]
This is [permitted content](https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Content_categories#Flow_content) for the `figcaption` element.

**Comment by oleq** [comment]
> Is it bug or feature? It works fine :)

A feature. If it's possible to format the caption's text in editor-classic, why not using the contextual toolbar? What worries me is why the balloon/toolbar have no proper styling.

**Comment by oleq** [comment]
This is what we need:
```diff
diff --git a/src/toolbar/contextual/contextualtoolbar.js b/src/toolbar/contextual/contextualtoolbar.js
index d3b635e..1667670 100644
--- a/src/toolbar/contextual/contextualtoolbar.js
+++ b/src/toolbar/contextual/contextualtoolbar.js
@@ -10,6 +10,7 @@
 import Plugin from '@ckeditor/ckeditor5-core/src/plugin';
 import ContextualBalloon from '../../panel/balloon/contextualballoon';
 import ToolbarView from '../toolbarview';
+import Template from '../../template';
 import BalloonPanelView from '../../panel/balloon/balloonpanelview.js';
 import debounce from '@ckeditor/ckeditor5-utils/src/lib/lodash/debounce';
 
@@ -48,6 +49,12 @@ export default class ContextualToolbar extends Plugin {
          */
         this.toolbarView = new ToolbarView( this.editor.locale );
 
+        Template.extend( this.toolbarView.template, {
+            attributes: {
+                class: 'ck-editor-toolbar'
+            }
+        } );
+
         /**
          * The contextual balloon plugin instance.
          *
```

**Comment by oskarwrobel** [comment]
We have this https://github.com/ckeditor/ckeditor5-ui/blob/master/src/toolbar/contextual/contextualtoolbar.js#L173.

It worked fine few days ago.

**Comment by oleq** [comment]
Moving discussion to https://github.com/ckeditor/ckeditor5-ui/issues/230.

**Comment by fredck** [comment]
It's a cool feature, but it would be even better if only allowed options would be visible.
