### ISSUE TITLE
Text alternative input should synchronise its value when the balloon shows up

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor5-image#114]
## Steps to reproduce
1. Select an image.
2. Choose "change image text alternative" from contextual toolbar.
3. Type "test".
4. Press "Save".
5. Repeat step 2.
6. Type "test2".
7. Press "Cancel".

## Current result
Text alternative changed.

## Expected result
Pressing "Cancel" should abort changing text alternative.

## Other informations
OS: Windows 10, Ubuntu 16.04
Release: 0.10.0

**Comment by oleq** [comment]
To start off, this is a twin to https://github.com/ckeditor/ckeditor5-link/issues/78.

It may look like the previous (canceled) value has been actually saved to the model but it's not true.  "Cancel" does not update the document but the value of the input is not refreshed when the balloon shows up. 

The fix similar to https://github.com/ckeditor/ckeditor5-link/pull/120/files is what we need (a one–liner, in fact).
