### ISSUE TITLE
Responsive Images handling

### ISSUE THREAD

**Issue by pjasiun** [ckeditor/ckeditor5-image#116]
Images should handle `srcset` attribute. It should be possible to set it in the model and should be properly converted to the view, letting the browser decide which source is used.

See https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Responsive_images

**Comment by pjasiun** [comment]
In fact, in the model, we can allow to set `src` as an object and the converter should convert it to `srcset` + `src` in the view.

**Comment by oleq** [comment]
A duplicate of https://github.com/ckeditor/ckeditor5-image/issues/2.
