### ISSUE TITLE
Improve visual styles of the image widget

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5-image#12]
To make it look like this

![image](https://cloud.githubusercontent.com/assets/1099479/20183667/6dca860a-a766-11e6-9758-ed37d531b0cf.png)

A follow-up of https://github.com/CKEditor5/ckeditor5.github.io/pull/22#issuecomment-263636369.

**Comment by fredck** [comment]
When it comes to the dragging handle, widgets that have non-editable content, like images, don't really need it as dragging could be started directly from within the widget itself. It would be more intuitive to users.

The handle could be introduced later when people will start developing widgets that have just (or mainly) editables inside.

**Comment by oleq** [comment]
This issue is not actually about drag handler but outlines for selected/hovered widget. The discussion that you have just started belongs to https://github.com/ckeditor/ckeditor5-image/issues/6 because it's pure UX.

**Comment by Reinmar** [comment]
Isn't it done already?

**Comment by Reinmar** [comment]
I guess it's not: https://github.com/ckeditor/ckeditor5-image/issues/45.
