### ISSUE TITLE
&#8203; characters are inserted while dragging selection over side image

### ISSUE THREAD

**Issue by oskarwrobel** [ckeditor/ckeditor5-image#121]
![jul-06-2017 10-02-39](https://user-images.githubusercontent.com/1057056/27901539-bfe27146-6232-11e7-98cc-254dfabc1f8d.gif)

**Comment by oleq** [comment]
Probably a dup of https://github.com/ckeditor/ckeditor5-image/issues/19.

**Comment by oskarwrobel** [comment]
Yes, it is.
