### ISSUE TITLE
Text alternative balloon should be displayed as read-only when command is disabled

### ISSUE THREAD

**Issue by oskarwrobel** [ckeditor/ckeditor5-image#123]
When `ImageTextAlternativeCommand` is disabled user should have access to the alternative text but should not be able to modify it.

**Comment by fredck** [comment]
I'm for not showing contextual toolbars at all, if the editor is readonly.

**Comment by pjasiun** [comment]
@fredck tell it here: https://github.com/ckeditor/ckeditor5-ui/issues/269 ;)

**Comment by oleq** [comment]
I'm closing this issue due to lack of discussion. I consider rejecting [this PR](https://github.com/ckeditor/ckeditor5-image/issues/124) the right decision and I'm moving the discussion to the somehow related https://github.com/ckeditor/ckeditor5-ui/issues/269.
