### ISSUE TITLE
updateCaptionVisibility throws when typing at the end of a link

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-image#127]
![jul-23-2017 22-58-13](https://user-images.githubusercontent.com/156149/28502790-6f3c004c-6ffa-11e7-91b5-62e07fef0093.gif)

I've got no idea why it throws but this happens in the situation I recorded. For some reason `viewSelection.editableElement` is undefined at that moment.

**Comment by scofalik** [comment]
I've seen this problem already and I am working on it ATM.

**Comment by Reinmar** [comment]
I'm encountering this pretty often, so let's give it a proper priority.

@szymonkups could you take a look on this?
