### ISSUE TITLE
Changing the orientation of the side image icon

### ISSUE THREAD

**Issue by wwalc** [ckeditor/ckeditor5-image#135]
It may be a bit related to #134.

What if a developer sets the style of .image-style-side to `float: left;`. Is there a way to change the sideIcon from `object-right.svg` to `object-left.svg` when using a CKEditor build?

**Comment by fredck** [comment]
It would be wonderful to have an easy configuration way to switch the icon with the left aligned one, if my website fits that. Something like this:

```
image-side-image-icon: 'right' (default) || 'left'
```

**Comment by oleq** [comment]
ATM it works like this https://github.com/ckeditor/ckeditor5-image/blob/master/src/imagestyle/imagestyleengine.js#L48. 

We could make it a config option and handle it in the `ImageStyleEngine`:
```js
import sideIconLeft from '@ckeditor/ckeditor5-core/theme/icons/object-left.svg';
import sideIconRight from '@ckeditor/ckeditor5-core/theme/icons/object-left.svg';
...
const sideIcons = { left: sideIconLeft, right: sideIconRight };
const sideIconConfig = editor.config.get( 'image.ui.sideIcon' );

// Allow the config value as 'left' or 'right' or '<svg>...</svg>'.
const sideIcon = sideIconConfig ? sideIcons[ sideIconConfig ] || sideIconConfig : sideIconRight;

...
    { 
        name: 'imageStyleSide', 
        title: t( 'Side image' ), 
        icon: sideIcon, 
        value: 'side', 
        className: 'image-style-side' 
    }
```
