### ISSUE TITLE
Weird behaviour of a list placed next to image aligned to the left

### ISSUE THREAD

**Issue by m-kr** [ckeditor/ckeditor5-image#144]
Bullets from the list placed next to an image aligned to the left disappear when image position is changed to full width or to the right.

![sep-28-2017 12-46-24](https://user-images.githubusercontent.com/8529247/30962669-ee749124-a44a-11e7-9d4d-cd6276092837.gif)

**Comment by Reinmar** [comment]
I saw a screenshot where someone commented that it's Chrome's bug. Was it you, @oleq?

**Comment by oleq** [comment]
Yes, I noticed it [here](https://github.com/ckeditor/ckeditor5-image/pull/140#issuecomment-330513497). I see no workaround at this moment.

**Comment by oleq** [comment]
I also reproduce it in v4

![image](https://user-images.githubusercontent.com/1099479/30962886-c695bfe2-a44b-11e7-9a64-fa4d82b8cc9c.png)

Any change to a parent containing the list fixes the position of the markers. It's probably a Chrome bug related to re-painting.

**Comment by Reinmar** [comment]
It's worth reporting. @oleq, will you set yourself a reminder to do so? :D

**Comment by Reinmar** [comment]
Resolved:

![image](https://user-images.githubusercontent.com/156149/64115373-bad43e80-cd8f-11e9-8158-74fbe806b43a.png)
