### ISSUE TITLE
Fix broken tests on other browsers than Chrome

### ISSUE THREAD

**Issue by pomek** [ckeditor/ckeditor5-image#153]
The main issue: https://github.com/ckeditor/ckeditor5/issues/615

Broken tests in this package:

- [x] Firefox 56.0.0 (Mac OS X 10.10.0) Image integration with the ContextualToolbar should prevent the ContextualToolbar from being displayed when an image is selected FAILED
- [x] Firefox 56.0.0 (Mac OS X 10.10.0) ImageEngine conversion in data pipeline model to view should convert srcset attribute to width, srcset and add sizes attribute FAILED
- [x] Edge 16.16299.0 (Windows 10 0.0.0) ImageEngine conversion in data pipeline model to view should convert srcset attribute to srcset and sizes attribute FAILED
- [x] Edge 16.16299.0 (Windows 10 0.0.0) ImageEngine conversion in data pipeline model to view should convert srcset attribute to width, srcset and add sizes attribute FAILED

In order to reproduce these issues, please follow this instruction – https://github.com/ckeditor/ckeditor5/issues/615#issuecomment-340414494 – _How to run it on my local machine?_

**Comment by pomek** [comment]
A few tests fail on Edge because of: `TypeError: Object doesn't support property or method 'Symbol.iterator'`. 

![image](https://user-images.githubusercontent.com/2270764/32481869-8001dc28-c395-11e7-97c8-5ada01a57fa2.png)

**Comment by pomek** [comment]
Firefox fails because of window/tab focus. It can be reproduced on dev machine. If you focus the tab with tests, a scenario will pass. If the focus is somewhere else, the scenario will fail.

**Comment by pomek** [comment]
> A few tests fail on Edge because of: TypeError: Object doesn't support property or method 'Symbol.iterator'.

It can be related to `engine/view` which does not pass on Edge as well.

**Comment by oleq** [comment]
> A few tests fail on Edge because of: TypeError: Object doesn't support property or method 'Symbol.iterator'.

https://github.com/ckeditor/ckeditor5-ui/pull/338 should fix that.

**Comment by oleq** [comment]
Please also take a look at [broken `Template.revert` test in Edge](https://github.com/ckeditor/ckeditor5-ui/issues/255). It requires improvements in the `normalizeHtml` test util.

**Comment by pomek** [comment]
After https://github.com/ckeditor/ckeditor5-ui/issues/337 Edge works fine. Thanks.
