### ISSUE TITLE
Can't leave the image focus

### ISSUE THREAD

**Issue by wenmingtang** [ckeditor/ckeditor5-image#156]
I have an example contents:

```
text
<uploadedImage>
```

<img width="890" alt="qq20171114-223131 2x" src="https://user-images.githubusercontent.com/1620172/32785188-81f9e8dc-c916-11e7-9610-3194b9068de7.png">

At this time, My cursor was sucked by the image,  can't leave. can't go down.
I hope to get your help.
Thanks.

**Comment by Reinmar** [comment]
Hi! Sorry to hear that. I have a couple of questions:

1. On which browser do you encounter this issue?
2. What do you mean by "can't leave" and "can't go down"? Could you describe the exact steps (what you do)?
