### ISSUE TITLE
typo in CSS classes naming

### ISSUE THREAD

**Issue by long-lazuli** [ckeditor/ckeditor5-image#167]
Refering to this document : https://github.com/ckeditor/ckeditor5-design/wiki/Code-Style-Naming-Guidelines

There is a typo in those classes :  
https://github.com/ckeditor/ckeditor5-image/blob/master/theme/textalternativeform.css

I expect this selector `[class^='ck-']` to match every CKEditor UI.

**Comment by Reinmar** [comment]
Thanks for noticing. We've got a ticket somewhere about reviewing these classes because there may be more of these.

**Comment by oleq** [comment]
Duplicate of https://github.com/ckeditor/ckeditor5-ui/issues/112.
