### ISSUE TITLE
Hover border is not visible after blurring an image

### ISSUE THREAD

**Issue by mlewand** [ckeditor/ckeditor5-image#170]
## Are you reporting a feature request or a bug?

Bug

## Provide detailed reproduction steps (if any)

1. Open [CKEditor 5 demo](https://ckeditor5.github.io/docs/nightly/ckeditor5/latest/examples/builds/classic-editor.html).
2. Focus the image.
3. Blur the image by clicking **outside of the editor** (if you blur by clicking somewhere else in the editor the issue does not occur).
4. Move cursor back over the image.

### Expected result

Focus border is applied to the image component.

### Actual result

No border is applied.

## Other details

* Browser: Chrome, Edge (didn't test more, seems to be cross browser)
* OS: Win 10

**Comment by oleq** [comment]
It is unlike v4's behavior but OTOH I'm not sure it's completely wrong.

**Comment by szymonkups** [comment]
I've marked is as confirmed but looking at this after your comment @oleq it's not that obvious. 
I think that this is by design - we are not applying any hover border color when image is selected. No matter if editor is focused or not.

**Comment by szymonkups** [comment]
We can discuss here if this decision is correct or not of course :smile:

**Comment by dkonopka** [comment]
As @oleq said, I don't see bad UX because of removed previous state of editor.

Still, it looks really weird (image toolbar is blinking:
![weird-image](https://user-images.githubusercontent.com/10219857/35683517-7d4cac02-0764-11e8-9f07-5a66c70413f3.gif)

Behaviour of creating link:
![create-link](https://user-images.githubusercontent.com/10219857/35683571-aef59746-0764-11e8-8d44-8aa2524151e2.gif)

**Comment by mlewand** [comment]
Just after your feedback I have noticed there is a fourth state where you have a gray outline around. So we have states like that:

* focused (blue)
* hovered (orange)
* active? (gray)
* default (none)

For me this behavior seems to be inconsistent. Feels like hover should take precedence over active? state.

**Comment by dkonopka** [comment]
There is any reason to show a state of the image when editor is blurred (gray border)?

```css
.ck-editor__editable.ck-blurred .ck-widget.ck-widget_selected {
	outline: 3px solid #ddd;
}
```

Hover (yellow border) and Focused (a blue one) shouldn't be enough?
