### ISSUE TITLE
[Docs] Add documentation about image text alternative to the Images guide

### ISSUE THREAD

**Issue by AnnaTomanek** [ckeditor/ckeditor5-image#194]
This feature is enabled by default, but it is important from accessibility point of view so it wouldn't hurt if we had a paragraph describing how it works in the [Images](https://docs.ckeditor.com/ckeditor5/latest/features/image.html) guide.

**Comment by mlewand** [comment]
There is some documentation regarding this feature. Also we didn't get any feedback that this is unusable from the community so this makes me think that the feature is well discoverable.
