### ISSUE TITLE
[Docs] Responsive images documentation

### ISSUE THREAD

**Issue by AnnaTomanek** [ckeditor/ckeditor5-image#195]
The TODO in the Responsive images section of the [Images](https://docs.ckeditor.com/ckeditor5/latest/features/image.html) guide is likely to stay with us forever so I'm creating an issue for it ;)

**Comment by Reinmar** [comment]
It's done already 🎉

![image](https://user-images.githubusercontent.com/156149/64958535-b760ad00-d88f-11e9-9757-3d06011dd840.png)
