### ISSUE TITLE
Failing image tests after recent refactoring

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5-image#198]
After [recent refactoring](https://github.com/ckeditor/ckeditor5-image/pull/193) 2 tests are failing https://travis-ci.org/ckeditor/ckeditor5-image/jobs/360209024.

Writing anything to the caption causes the `.ck` class to vanish in the view

```js
model.change( writer => {
	writer.insertText( 'foo bar', caption );
} );
```

**Comment by oleq** [comment]
It turns out it's a collision with the placeholder management and its classes (it controls `.ck`) https://github.com/ckeditor/ckeditor5/issues/931. It should never lose this class.

**Comment by Reinmar** [comment]
Maybe the placeholder logic should not care about the `.ck` class? The styles can depend on it because, at the same time, the assumption may be that the placeholder will be used on an element which already has this class. WDYT?

**Comment by oleq** [comment]
> Maybe the placeholder logic should not care about the .ck class? The styles can depend on it because, at the same time, the assumption may be that the placeholder will be used on an element which already has this class. WDYT?

Maybe you're right. OTOH one can create a placeholder out of any content element (see the placeholder MT). In this case, there isn't much we can do to make it look right (the `.ck` class). I'm not sure what to do about that.

**Comment by Reinmar** [comment]
In the documentation of this util and of the widget selection (@dkonopka mentioned something about it) we may state that it can only work if the base element has the `.ck` class. In fact, in the widget's case its `toWidget()`'s role to assign this class so you don't need to do anything more.

**Comment by oleq** [comment]
Makes sense to me. @szymonkups WDYT?

**Comment by szymonkups** [comment]
> In the documentation of this util and of the widget selection (@dkonopka mentioned something about it) we may state that it can only work if the base element has the .ck class. In fact, in the widget's case its toWidget()'s role to assign this class so you don't need to do anything more.

It would be cleaner solution to me too. I'll fix this PR.

**Comment by szymonkups** [comment]
I am just wondering about use cases without widgets. As in Letters: we want to add a placeholder to the first paragraph and title. We would need some additional code to insert a `.ck` class there. Is that acceptable?

**Comment by oleq** [comment]
> I am just wondering about use cases without widgets. As in Letters: we want to add a placeholder to the first paragraph and title. We would need some additional code to insert a .ck class there. Is that acceptable?

That's a good point, actually. It feels like the placeholder should add `.ck` after all.

It just came to my mind (*thinking aloud*), do we need to remove the `.ck` class at all? Would it make any difference? All selectors in CSS are `.ck.something`. Standalone, it should not do anything.

**Comment by dkonopka** [comment]
IMHO we should care about `.ck` class, let's look at this issue in [ckeditor5-collaboration repo](https://github.com/cksource/ckeditor5-collaboration/issues/180).

Now imagine scenario: 

User selection (`ck.ck-user__selection`) on the image (`.ck.ck-widget`). 
When the user disconnects or changes this selection it means removing (`ck.ck-user__selection`) from the widget. And then `.ck` class vanishes from a widget.

https://github.com/cksource/ckeditor5-collaboration/blob/master/src/users/usermarkers.js#L104-L124

**Comment by Reinmar** [comment]
@szymonkups made a good point. I assumed that the developer who adds the placeholder to his/her element can freely do whatever he/she wants with it. But in this case, it would be cumbersome for developers. It's ok, but not cool. 

The alternative is a similar solution to what @szymonkups proposed in https://github.com/ckeditor/ckeditor5-engine/pull/1391. But that's quite cumbersome for us instead. 

TBH, both solutions are equally bad :D One of the parties will suffer. In such a case – we can do whatever, but let's be consistent.

Since @szymonkups looks good I think we can go this way. But we also need to make a similar fix for `.ck.ck-user__selection`.

**Comment by Reinmar** [comment]
Followup in https://github.com/ckeditor/ckeditor5/issues/936.
