### ISSUE TITLE
Possibility to use DIV container for gallery-like purposes

### ISSUE THREAD

**Issue by designbuedchen** [ckeditor/ckeditor5-image#199]
Hey there, I would like to extend the editor with some sort of gallery function. My goal is something like this for the view:

```
<div class="gallery">
  <figure class="image">
    <img>
    <figcaption>FOO</figcaption>
  </figure>
  <figure class="image">
    <img>
    <figcaption>BAR</figcaption>
  </figure>
  <figure class="image">
    <img>
    <figcaption>FOOBAR</figcaption>
  </figure>
</div>
```

Is there a way to extend the editor right now at this stage without extending the standard model? Maybe it's not a bad idea to have some sort of grouping order, having all those figures grouped into one div gives the frontend a way to render some sort of gallery function. It would help me to get to know a good starting point, maybe in another plugin.

Thanks in advance for the help.

**Comment by scofalik** [comment]
The feature you are aiming for seems to have rather simple "model and view" requirements. You'd only need to ask yourself how sophisticated UI/UX you want to make (on the editor side). It could be a simple one: just insert some kind of box, like Blockquote feature, and insert images into it. It will not look the nicest but it's easy to bootstrap. On the other side of the spectrum, you'd have some developed UI and there are multiple possibilities. Maybe you would also want some more complicated CSS and even JS to simulate how the gallery would look like.

Keep in mind, though, that you cannot add any new feature "without extending the standard model", and a gallery is not a feature that we have or think about. "Standard model" is a funny phrase itself, cause there's nothing like the standard model -- even official builds differ when it comes to included plugins and every plugin extend the model. The whole idea behind the model is that it is easily extendable, so third-party programmers can easily write their features.

**Comment by designbuedchen** [comment]
Thanks for your answer @scofalik!

I'm sorry for my "noobish" posting. I made a lot of improvements the last 2 days. Indeed the [blockquote](https://github.com/ckeditor/ckeditor5-block-quote) plugin was a good starting point for me. Right now I'm a little bit stucked on a selection problem. It's easy to get the container element with an onclick event, but I want to achive getting the element by the selection of model.document.selection.

I really love the editor and many things are done totally right. But being totally new to the ckeditor-world makes it hard to understand.

I will close this topic, since it doesn't help improving the plugin itself. But thanks anyway! ;-)

**Comment by scofalik** [comment]
If you want to be able to select the container element, I think you should take a look at the Image plugin and how widgets are created and used. It is not the easiest read, but images are elements which are selectable.

PS. The question was not "noobish" just "funny", especially since [standard model](https://en.wikipedia.org/wiki/Standard_Model) is a thing :).
