### ISSUE TITLE
Add confirmation check mark to the image upload animation

### ISSUE THREAD

**Issue by pjasiun** [ckeditor/ckeditor5-image#204]
There should be :white_check_mark: when the upload finish sucessfully.

This is how it looks now in CKEditor 5:

![before](https://user-images.githubusercontent.com/1166967/39767495-34d9f870-52e7-11e8-838d-e9f9363716be.gif)

This is how the animation looks like in Letters (with check mark):

![after](https://user-images.githubusercontent.com/1166967/39767501-39f7d5ca-52e7-11e8-84de-0135a50d55b1.gif)

Without it, upload looks incomplete.

**Comment by pjasiun** [comment]
BTW, apparently, there is something wrong with chack mark style, it is too small. It should be of course fixed.

**Comment by jodator** [comment]
One comment: I've totally missed that check mark while watching the animation for the first time. Wouldn't be better to put it on the left side of an image?

**Comment by dkonopka** [comment]
IMHO loader bar is appearing from the left to the right and this is the proper direction which user eyes should follow.

cc @oleq

**Comment by jodator** [comment]
> IMHO loader bar is appearing from the left to the right and this is the proper direction which user eyes should follow.

Maybe the bar also should be a bit bigger as it's also easy to miss - upload is very fast on your gifs. 

Anyway I think that you guys now the best here, I've just dropping my 2¢ ;)

**Comment by pjasiun** [comment]
Keep in mind that the reason for this tickets is to unify upload UI in Letters and CKE 5, not to redesign it. If, by the way, you can make it better easily it would be great, but I remember we had a really long talk about the thickness of the bar, animation, etc and I don't want to reopen this discussion here. If you find something wrong in the upload UI feel free to report a separate ticket about it.
