### ISSUE TITLE
Consider changing image upload placeholder

### ISSUE THREAD

**Issue by dkonopka** [ckeditor/ckeditor5-image#207]
At this moment we are using [svg as placeholder](https://github.com/ckeditor/ckeditor5-image/blob/master/theme/icons/image_placeholder.svg) with plain text `Uploading image...` and progress bar animation. The problem is there is no way to translate this text, because it's hardcoded in the `svg` file. 

<img width="820" alt="upload-placeholder" src="https://user-images.githubusercontent.com/10219857/40049364-e0d6de3e-5834-11e8-9098-6c8d0c037afa.png">

We should think about something like centered spinner instead of plain text.

cc @oleq @Reinmar

**Comment by dkonopka** [comment]
I've made research and there is no perfect solution to change current placeholder. I was thinking about two possibilities: 

**1. Inline SVG animation**

It is so simple and perfect solution to display inline [SVG animations (SMIL)](https://developer.mozilla.org/en-US/docs/Web/SVG/SVG_animation_with_SMIL), but sadly there is no [Edge support](https://caniuse.com/#search=SMIL) :( 

**2. CSS Animation**

There was a solution also, but in our case where `svg` is transformed to base64 into `img[src]`there is no way to control it via CSS.

**3. New element inside `<figure>`**

I don't know if it is ok to crete new element inside figure while uploading. 

## Proposal

Let's use animated SVG and create nice-looking first frame of loader (which will be displayed as static on Edge). Note: placeholder has grey background, it's about screencast quality and it's not final proposal, we just need to decide about loader.

### Every browser (Chrome, Safari, FF)

![loader-v1](https://user-images.githubusercontent.com/10219857/40306573-776d9a6c-5cff-11e8-8bd6-1dca41fee5c7.gif)

### ...and Edge

![edge-loader](https://user-images.githubusercontent.com/10219857/40306877-9cb543c8-5d00-11e8-90d7-723b25db8050.gif)

## Question

If we'll decide to go with animated, centered loader, should we remove infinite progress bar for the user?

**Comment by oleq** [comment]
> I don't know if it is ok to create new element inside figure while uploading.

I think that would be the easiest way because it allows CSS animations to create some beautiful placeholders. What about the engine side, though? cc @scofalik

**Comment by oskarwrobel** [comment]
> I think that would be the easiest way because it allows CSS animations to create some beautiful placeholders. What about the engine side, though? cc @scofalik

We already do it to show upload progress bar or upload complete icon. ez.

**Comment by oleq** [comment]
Let's switch to CSS then. You can create [awesome](http://tobiasahlin.com/spinkit/) animated [stuff](https://loading.io/css/) with it. 

@dkonopka can you come up with the right, subtle style for us, maybe (?) together with some text (which will be localizable in that situation) and propose something?

**Comment by dkonopka** [comment]
So, you can find here proposals of loaders based on single `div` or `span` (except text container). 
https://codepen.io/k0n0pka/full/KeKdbd/

By the way, exists a lot of beautiful CSS-only loaders, but based on plenty of spans, I'm not so sure about performance in that case.

WDYT guys, should we go with default "spinner" or choose something modern like moving balls?
