### ISSUE TITLE
Icons for default image styles 

### ISSUE THREAD

**Issue by szymonkups** [ckeditor/ckeditor5-image#21]
As we decided here https://github.com/ckeditor/ckeditor5-image/issues/18#issuecomment-266785037 we will start with Full+Side. Icons for that default styles will be needed.

![image](https://cloud.githubusercontent.com/assets/2396463/21308693/5cdec732-c5db-11e6-804e-cd122e239779.png)

**Comment by oleq** [comment]
The icons are ready but I got to export them. Stay tuned!

**Comment by fredck** [comment]
Can we have the Side icon to the right?

**Comment by fredck** [comment]
I mean, it is rarer to have images aligned left inside articles, so let's default it to the right.

**Comment by oleq** [comment]
Er. I'll provide object-side-[left,right] and object-center icons. They're free to use for any feature.

**Comment by szymonkups** [comment]
Icons landed in core https://github.com/ckeditor/ckeditor5-core/pull/56
