### ISSUE TITLE
The insert image button is enabled in table

### ISSUE THREAD

**Issue by jodator** [ckeditor/ckeditor5-image#225]
...but you cannot place an image inside table cell:

![selection_016](https://user-images.githubusercontent.com/247363/42636324-c4ca55b8-85e8-11e8-9ae7-f95f9cf455bc.png)

**Comment by oleq** [comment]
I wanted to extend the fix to also consider https://github.com/ckeditor/ckeditor5-image/issues/227 but I found out that if I disable the command when another image is selected, it fails to insert multiple images. IMO multi-upload should not rely on that but I didn't thoroughly check how it works either.
