### ISSUE TITLE
Why is the upload button enabled when the image is selected?

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5-image#227]
The enabled button suggests that some action (?) in the context of the selected image can be performed. But clicking it only uploads another image next to the selected one. 

It could be confusing IMO.

![image](https://user-images.githubusercontent.com/1099479/42813574-c0bfee38-89c1-11e8-9784-229a0c98c5b5.png)

cc @dkonopka

**Comment by pjasiun** [comment]
I believe it should be consistent.

At the moment, if an object is selected, the image will be inserted after that object (note that image is not inserted in the position of the selection, but it uses `findOptimalInsertionPosition` util). If we decide that the button should be disabled on such a position, the command should do nothing. If we disable the button, but `command.execute` will still execute its action (and insert image after) it will be strange.

Also, I think that this behavior should not be limited to the image. I think it should work like this for inserting images on all objects, or even more generic, for inserting all objects (which uses `findOptimalInsertionPosition`) when an object is selected. So whenever an object is selected and I want to insert an object the button should be disabled.

Alternatively, we could replace one object with the other in such cases.

**Comment by jodator** [comment]
> f we disable the button, but `command.execute` will still execute its action (and insert image after) it will be strange.

Actually the proposition is to disable command not the button so the `command.execute()` will not insert image. But yes - we should agree on how it will work.
