### ISSUE TITLE
ImageLoadObserver fire imageLoaded 3 times

### ISSUE THREAD

**Issue by stepan-perlov** [ckeditor/ckeditor5-image#243]
Hi,

I need execute callback, when image loaded.
I finds ImageLoadObserver with imageLoaded event.
```javascript
editor.editing.view.document.on('imageLoaded', (domEvent)=> {
    console.log('imageLoaded', domEvent);
});
```
This callback fires 3 times on one image uploading. In domEvent no information, about what is. (no element reference, no state reference)

This is normal behaviour? ckeditor/image has another way for implementing my case?

**Comment by Reinmar** [comment]
cc @oleq

**Comment by oleq** [comment]
Hi @stepan-perlov!

The `imageLoaded` event is a low–level one. It fires whenever the native DOM `load` fires and this can happen a lot once you e.g. drop an image into the content. For instance, it will fire when the image preview (base64) is displayed (but still uploading) and then again when the actual URL returned by the server replaces the base64 blob. This change is transparent to the user, but not to the `load` event fired by `<img/>` again and again.

> ckeditor/image has another way for implementing my case?

Can you tell us more about your issue and use-case? What would you like to know exactly?

Generally speaking, I'd rather use the `FileRepository` API to learn about the uploading process but again, I'm not sure what's your goal here so it's hard to give you any good advice.

```js
editor.plugins.get( 'FileRepository' ).loaders.on( 'add', ( evt, loader ) => {
	console.log( 'Added an upload loder', loader );
	console.log( 'The file is', loader.file );

	loader.on( 'change:uploadedPercent', ( evt, name, uploadedPercent ) => {
		console.log( `Upload progress: ${uploadedPercent}%` );

		if ( uploadedPercent == 100 ) {
            const range = editor.model.createRangeIn( editor.model.document.getRoot() );

            for ( const item of range.getItems() ) {
                if ( item.is( 'element', 'image' ) && item.getAttribute( 'uploadId' ) === loader.id ) {
                    console.log( 'Model element of uploaded image', item );
                }	
            }
        }
    } );

    loader.on( 'change:status', ( evt, name, status ) => {
		console.log( `Upload status: ${status}` );
    } );
} );
```

**Comment by stepan-perlov** [comment]
@oleq thanks.

I'm not found solution in documentation for callback on image uploaded.
In source code I found imageLoaded event and used it.
