### ISSUE TITLE
Image captioning

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-image#28]
First topic to discuss – what should be the data model and how we can implement the behaviour that the caption appears once you focus the image.

There are a couple of options, but none seems to be perfect:

1. Handle this upon conversion – in the model there will be no `<caption>` element when the image doesn't have caption. When you focus the image, the caption converter (hooked to selection change event) will add it to the *view*. This means, that the `<caption>` will be added to the model once you start typing and should be removed once you delete all the text (even before you blur the caption).
2. The second option is to always create the `<image>` element with a `<caption>` inside in the model, regardless of whether it has any content or not. And then, if it's empty, don't render it to the view.

The problems with the 1st option:

* You can have a `<figcaption>` element in the view, but no `<caption>` in the model, which means that there will be unmapped elements. This will be especially weird if you can place the selection in the rendered `<figcaption>`, but you can't map it to the model (cause there's no `<caption>` there).

The problems with the 2nd option:

* How can we force creating `<caption>` every time an `<image>` is created? These features don't know much about themselves and it needs to be automated somehow. E.g. the image upload feature will not know whether it should create the caption or not. The possible solution could be to create a post-fix listener on the model's insert event. The listener would add missing captions. It would be registered by the image caption feature.

  This may not sound like an elegant solution, but in fact, that's how we wanted to implement rules which a static schema will not able to enforce. There were two options in the past:

  * Either the schema would contain logic which is able to fix the model after e.g. OT broke it.
  * Or we can have a static schema (as a definition what is correct and what not) and listeners which post-fix broken model.

  So, the propose solution is in line with that.

**Comment by fredck** [comment]
+1 for the 1st option, especially because I'm afraid this will be a common case and we need to figure out how to handle it.

**Comment by Reinmar** [comment]
cc @pjasiun @scofalik

**Comment by scofalik** [comment]
I am for second option. It seems that there is less "moving parts" here and it just feels safe (especially when you think of model->view conversions and OT).

What you described is not really any post-fixing or anything. I mean, it shouldn't be seen as something negative. From the beginning of `model.Document#event:change` we accepted that some features may listen to that event and react to changes. `ImageCaption` could just listen to that change event and check whether image is inserted without `<caption>`.

Actually the mechanism for 1st and 2nd idea is similar, but you would listen to other stuff. However the mechanism from 2nd idea would do changes only once, while the other would do changes all the time.

BTW. The way this caption looks like or behave in DOM or view should not have anything to do with model. We cannot use model to show/hide elements in view (upon focusing).

My only doubt is if there is semantial/logical/data difference between empty caption and not having any caption, because with 2nd idea we always have `<caption>` element so we can't differentiate between those two states.

**Comment by Reinmar** [comment]
> My only doubt is if there is semantial/logical/data difference between empty caption and not having any caption, because with 2nd idea we always have <caption> element so we can't differentiate between those two states.

The way how it works visually (that when the caption is empty it always disappear) makes these 2 states identical.

It could and need to work differently in the model if it worked differently in the view. E.g. if we had a button to toggle caption on/off we'd have to implement this differently in the model too. But then the `<caption>` wouldn't need to be added for every image, so it wouldn't have to happen automatically.

**Comment by pjasiun** [comment]
First, I preferred the solution no. 1. It looks more semantically correct. But then, I started thinking about the selection and it fact it is a problem how to represent the selection in the caption when there is no caption. I do not think we should mark the selection in any other model element if it is in the caption (it could be directly in the `<image>`, but it can not contain text, so the selection should not be there) and I do not think we should dynamically create the `<caption>` element in the model when the selection go there. If we do so, we may have a problem with the collaboration that we create the element for other users. In general selection change in view should only cause selection change in the model, not changing the structure.

This is why I prefer option 2: keep the `<caption>` element to have a good place to put the selection if needed.

**Comment by pjasiun** [comment]
On the other hand, there should not be any big issue connected with creating and removing caption element and it might be fine as well.

I think the solution we choose should depend on how we see it:

 - if we assume that the caption is there, only hidden, we should go with option 1,
 - if we assume that the caption does not exist and we want to create it when the image is clicked, the option 2.

From the technical point of view both should be fine.
