### ISSUE TITLE
Image srcset on custom media insert

### ISSUE THREAD

**Issue by dannybarinshtein** [ckeditor/ckeditor5-image#281]
Hello,

I am using the editor API to insert images from a custom built media library.

I have the following snippet:

```
editor.model.change(writer => {
	const imageElement = writer.createElement("image", {
		src: imageUrl,
		alt: alt
	});

	editor.model.insertContent(
		imageElement,
		editor.model.document.selection
	);
});
```

The only thing I can't figure out is how to add srcset to it.. I read a few closed issues where it says srcset requires sizes as well, or that the srcset attribute has been changed to responsive with the srcset and sizes being attributes inside of it.

Is there a better approach to image insertion here? Or am I missing something else?

Any assistance would be greatly appreciated.

**Comment by Reinmar** [comment]
cc @Mgsy

**Comment by Mgsy** [comment]
Hi, @dannybarinshtein, sorry for a late response. In our model `srcset` attribute is represented like this:
```
srcset="{"data": "url", "width": int}"
```

Here is the example:
```
srcset={"data":"https://33333.cdn.cke-cs.com/rc1DFuFpHqcR3Mah6y0e/images/81c7dd4a263b4719ce5761fce9b4c1024b1a12a7bce1ad90.jpg/w_115 115w, https://33333.cdn.cke-cs.com/rc1DFuFpHqcR3Mah6y0e/images/81c7dd4a263b4719ce5761fce9b4c1024b1a12a7bce1ad90.jpg/w_195 195w, https://33333.cdn.cke-cs.com/rc1DFuFpHqcR3Mah6y0e/images/81c7dd4a263b4719ce5761fce9b4c1024b1a12a7bce1ad90.jpg/w_275 275w","width":275}
```

Give us a sign if you managed to solve your problem.

**Comment by Mgsy** [comment]
Closing it due to a lack of activity.
