### ISSUE TITLE
Data model representation of image feature

### ISSUE THREAD

**Issue by szymonkups** [ckeditor/ckeditor5-image#3]
I would like to discuss how image feature should be stored in the data model. Proposed solution:

```
<image alt="..." src="...">
    <caption>Image caption</caption>
</image>
```

Caption is stored as a separate element. This way caption text can store additional attributes, for example: `bold` or `italic`.

**Comment by scofalik** [comment]
AFAIR this is what we came up with after initial discussions. 👍 from me.

**Comment by Reinmar** [comment]
Two important factors to keep in mind:

1. Image captions are extension of basic image feature. We'll need to understand how their conversion needs to be plugged in.
2. Image can have more editable regions than only caption, so that's why we can't simply do: `<image>Caption text</image>`.
