### ISSUE TITLE
Should we have "Alternative text" or "Alternate text"?

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-image#37]
In MDN, CKEditor 4 and HTML 5 spec it's "alternative text". "Alternate text" is more popular in Google, but I think that "alternate" is a verb here.

**Comment by Comandeer** [comment]
I think we should stick to the HTML5 specification, which define `[alt]` as "alternative". The same word is used in WCAG 2.0 guidelines in this context (however they use it as ["text alternative"](https://www.w3.org/TR/WCAG20/#text-altdef)).

**Comment by Reinmar** [comment]
So, let's stick to what we have in CKE4 – Alternative text.

**Comment by Reinmar** [comment]
Ok, so we'll switch to "Image text alternative". Feature name will be `ImageTextAlternative`.
