### ISSUE TITLE
Fix the extend-template-render warning

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-image#42]
UI lib introduced a warning about extending already rendered templates and it turns out that the image feature logs a lot of them:

https://travis-ci.org/ckeditor/ckeditor5-image/builds/195804693#L1452

**Comment by Reinmar** [comment]
The problem is here:

```js
		const panel = this._panel = new ImageBalloonPanel( editor );
		const promises = [];
		const toolbar = new ToolbarView();

		// Add CSS class to the panel.
		Template.extend( panel.template, {
			attributes: {
				class: [
					'ck-toolbar__container'
				]
			}
		} );

```

And... well, ping @oleq for a solution ;>

**Comment by oleq** [comment]
The solution is: extend first, render next. And by "render", I mean "access `View#element`", which renders the element on demand.

**Comment by Reinmar** [comment]
Yeah, but what's accessing `#element` in this case? It must be `ImageBalloonPanel` itself.

**Comment by Reinmar** [comment]
`ImageBalloonPanelView#constructor`:

```js
		// Let the focusTracker know about new focusable UI element.
		editor.ui.focusTracker.add( this.element );
```

This would need to be moved to init().
