### ISSUE TITLE
The image must extend $block

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-image#54]
As explained in https://github.com/ckeditor/ckeditor5-engine/issues/532#issuecomment-280919795.

It's a part of bigger refactoring which we need to make.

**Comment by scofalik** [comment]
I wonder whether we should re-think what kind of abstract definitions we have in schema. Maybe having `$block` is just incorrect?

**Comment by Reinmar** [comment]
That's still open for me too. But I don't think that "block" is that bad. Image is a block element after all. It's just not a text container.

**Comment by Reinmar** [comment]
Handling block images correctly will require https://github.com/ckeditor/ckeditor5-engine/issues/894.

**Comment by Reinmar** [comment]
Once we'll make image a block, we also need to check if it's correctly handled in some merging scenarios on <kbd>Backspace</kbd>. E.g. https://github.com/ckeditor/ckeditor5-engine/pull/907#issuecomment-291823287

**Comment by Reinmar** [comment]
We made caption inheriting from blocks in https://github.com/ckeditor/ckeditor5-image/pull/95/files which introduced https://github.com/ckeditor/ckeditor5-block-quote/issues/10 ;<.

**Comment by Reinmar** [comment]
This was fixed once we refactored the schema. The `$block` element was detached from the `isBlock` property. Now, the image can have `isBlock`, be "allowed where `$block` is", but it's also `isObject` so it's filtered out properly by e.g. the list feature.
