### ISSUE TITLE
Ctrl+A in a nested editable must select that nested editable's content

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-image#55]
Right now, when you press `Ctrl+A` the selection is moved out of the nested editable. This needs to be handled by widgtes.

**Comment by oleq** [comment]
Side question: Why doesn't <KBD>CTRL</KBD>+<KBD>A</KBD> select the content of the editor in http://localhost:8125/ckeditor5-image/tests/manual/caption.html? Some missing plugin?

**Comment by Reinmar** [comment]
No. This happens because the editor's content ends with a cE=false element. Blink's and Webkit's selection implementations are limited and don't allow placing one of the boundaries in such a place. So CTRL+A does nothing in such a case.

The most reasonable solution I can think of is handling CTRL+A manually and patching renderer so it creates space at the beginning/end of the editable so the boundary can be rooted there.

**Comment by Reinmar** [comment]
But all this is a separate issue. It's not related to CTRL+A inside a nested editable.

**Comment by oleq** [comment]
Thanks, I was just curious.
