### ISSUE TITLE
Fix the image text alternative icon

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-image#59]
Right now it's some stock icon of an input IIRC.

**Comment by fredck** [comment]
I would definitely link this icon to accessibility.

**Comment by oleq** [comment]
That sounds like a plan. And since text alternative is almost exclusively used by screen readers, I think we should clearly tell the user about its purpose, like

![image](https://cloud.githubusercontent.com/assets/1099479/23359457/98c9f8ba-fce6-11e6-816c-4cce4e6e3432.png)

WDYT?

**Comment by Reinmar** [comment]
Hm... I'd be afraid that a normal user has no knowledge that a content of a web page must be "readable" so there will be no association between the speaker and what is it for.

**Comment by oleq** [comment]
I'm afraid it's very hard to express the purpose of the alt in a **simple** icon. And since all the icons must be simple, I'm limited to the very basic symbolics only.

> I'd be afraid that a normal user has no knowledge that a content of a web page must be "readable"

Me too. OTOH, this is the only real purpose of alt and if we expect people to create the content which is semantically correct, there isn't much we can do about the way we communicate it.

Maybe let's try some another way: what comes to your mind when you think about text alt?

**Comment by Reinmar** [comment]
Text alt gives the blind users the ability to "see" the image. I've checked some symbols with "accessibility" keyword:

* http://marketingland.com/wp-content/ml-loads/2015/08/accessibility-800x450.png
* https://css1.www.haltonhealthcare.on.ca/site_Files/Content/accessibility.jpg
* http://www.wellington.ca/en/government/resources/173img1.jpg

There's that icon of a crossed eye. WDYT about the one with two different halves of an eye? One clear and one "fogged"?

**Comment by Reinmar** [comment]
My line of thought is that such an icon, when used next to an image, a purely visual thing, may ring the right bells.

**Comment by oleq** [comment]
I checked this blurred eye symbol and it stands for "low vision", which is nothing like text alt. We cannot misuse commonly recognized symbols, I'm afraid.

**Comment by oleq** [comment]
TBH, we're closed to [Closed Captioning symbol](https://en.wikipedia.org/wiki/Closed_captioning) in this case except that text alt is for still images only.

**Comment by Reinmar** [comment]
> I checked this blurred eye symbol and it stands for "low vision", which is nothing like text alt. We cannot misuse commonly recognized symbols, I'm afraid.

What's wrong with low vision? Low vision + image gives you what? I don't know what would be my first guess and what would be any other person but at least the tips should be clear themselves. And then you have a label to check which says "text alternative", so when you combine this with "low vision" I think you should be close the answer.

**Comment by Reinmar** [comment]
> TBH, we're closer to Closed Captioning symbol in this case except that text alt is for still images only.

I didn't know that those "CC" letters stay for "closed captioning" and "closed captioning" said nothing to me. It's not an international symbol IMO yet and its rooted in English.

An eye is a better symbol IMO.

**Comment by oleq** [comment]
This eye symbol could suggest that the button changes the visibility of the image, hides it or something. I'll give it a try though.

**Comment by Reinmar** [comment]
BTW, it's a bit of an off topic, but WDYT about changing the color of the icon to red if the alt is empty?

**Comment by fredck** [comment]
What about the accessibility symbol, much like the one that we have in the A11y Checker?

**Comment by fredck** [comment]
> BTW, it's a bit of an off topic, but WDYT about changing the color of the icon to red if the alt is empty?

I would not go with anything like that right now. These are the kinds of things that must be extremely well thought before decided.

**Comment by Reinmar** [comment]
> What about the accessibility symbol, much like the one that we have in the A11y Checker?

That icon has no meaning for me – I'd have no idea what it means if I've seen it in the image toolbar. While it may be used to mark entire feature such as a11y checker, IMO, it will be super confusing in the image context.

**Comment by Reinmar** [comment]
> I would not go with anything like that right now. These are the kinds of things that must be extremely well thought before decided.

I didn't mean to think too much on this now, but whether the idea may make any sense. I'll report a ticket for it.

**Comment by oleq** [comment]
With low–vision icon: 

![image](https://cloud.githubusercontent.com/assets/1099479/23365050/bc775904-fd01-11e6-8baa-48eb30c6da75.png)

**Comment by Reinmar** [comment]
It was my idea so I rest my vote. But I like it :D 

Let's post it somewhere on our channels and see what's the reception.

**Comment by oleq** [comment]
Something like this maybe instead:

![image](https://cloud.githubusercontent.com/assets/1099479/23365263/b361c7b8-fd02-11e6-83da-b69ee926daf1.png)

**Comment by Reinmar** [comment]
Y... "is that a ninja T, mum?" :P 

Really, let's not overcomplicate this. An eye has a clear association with sight. "T" has no.

**Comment by fredck** [comment]
The eye thing is not bad. The speaker is a no-go for me, as well as the T.

**Comment by oleq** [comment]
Alright, let's stick with the eye. I'll create a PR for this.
