### ISSUE TITLE
Use separators in ImageToolbar to improve UX

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5-image#64]
A follow–up in https://github.com/ckeditor/ckeditor5-ui/issues/154.

**Comment by Reinmar** [comment]
It's much better than what we had:

![image](https://cloud.githubusercontent.com/assets/156149/23412762/f2b57714-fdd6-11e6-8303-c175919a87eb.png)

The order of buttons will be fixed once we'll resolve https://github.com/ckeditor/ckeditor5-image/issues/60.
