### ISSUE TITLE
Moving selection from nested editable to the image freezes the editor

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-image#73]
![mar-14-2017 14-12-19](https://cloud.githubusercontent.com/assets/156149/23902144/59ec84f6-08c0-11e7-81e4-30280131192e.gif)

It's also sometimes impossible to focus the widget back after you had the selection in the nested editable. There's no inf loop then, but something blocks the selection anyway.

**Comment by fredck** [comment]
> Grammarly?

😆

**Comment by Reinmar** [comment]
I have it disabled. And I even checked that with the addon totally disabled it still occurs. I'll check on updated Chrome.

**Comment by Reinmar** [comment]
Nope, still crashes.

The exact steps:

1. Click in the middle of the bold word in the caption.
2. Press Ctrl+b.
3. Type few letters.
4. Click the image.
5. Boom.

**Comment by oleq** [comment]
Got it too, thanks.

**Comment by oleq** [comment]
I'm unable to reproduce this issue. Can you still confirm it @Reinmar?

**Comment by Reinmar** [comment]
Nope.
