### ISSUE TITLE
Merge Widget and WidgetEngine plugins

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-image#75]
That code in `WidgetEngine` doesn't make much sense alone. Just like the rest of the code in `Widget` it handles the visual aspects of being a widget.

**Comment by szymonkups** [comment]
What about usage of this merged plugins? For example: now `ImageEngine` requires just `WidgetEngine` and `Image` requires `Widget`.

**Comment by Reinmar** [comment]
For me, being "widgety" is a purely visual (UI related) aspect, so everything about it should go to `Image`. The only thing `ImageEngine` needs to care about is schema and conversion – so data manipulation and data itself.

**Comment by szymonkups** [comment]
Moved to https://github.com/ckeditor/ckeditor5-widget/issues/4.
