### ISSUE TITLE
Allow bare <img> to be converted to model

### ISSUE THREAD

**Issue by szymonkups** [ckeditor/ckeditor5-image#8]
Right now conversion for from view in data pipeline is very strict and only converts images represented by:
```html
<figure class="image">
    <img src="..." alt="..." />
</figure>
```
We should allow single `<img>` (not wrapped in a `<figure>` element) to be converted to model image.

**Comment by szymonkups** [comment]
Also, it might be worth checking if view to model conversion could not be simplified by using view converter builder, and if not - propose a solution to possibly extend builder with missing functionalities.

**Comment by Reinmar** [comment]
I also mentioned another case in https://github.com/ckeditor/ckeditor5-image/issues/11 where a containing block will need to be split upon conversion to model.

**Comment by Reinmar** [comment]
> Also, it must also accept images inside e.g. `<p>`. I'm not sure how this should be handled upon conversion to the model, but it seems that the <paragraph> needs to be split.

So in the view we've got (let's assume it was pasted):

```html
<p>x<img>x</p>
```

In the model `paragraph` cannot contain an `image`. By default, in such situation, we're filtering out the content which is not allowed in its parent. But in this specific situation, most likely, we'll want to preserve the image. So the block must be split.

The idea that @scofalik and @pjasiun proposed is to first convert the image into the `<paragraph>` element in the model (against schema's rules) and then, in a late `<paragraph>` converter post-fix this. This will be a special rule for a special case, cause, as I mentioned, in majority of cases, we're interested in filtering out disallowed stuff.

**Comment by Reinmar** [comment]
Related thread: https://github.com/ckeditor/ckeditor5-paragraph/issues/11.

**Comment by scofalik** [comment]
PR adding conversion of bare `<img>` elements.

https://github.com/ckeditor/ckeditor5-image/pull/97

I feel that `<p>x<img>x</p>` is a different problem and I will create a new issue for it.
