### ISSUE TITLE
The image loses responsiveness when wider than its original size

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5-image#87]
ATM, when the editor is wider than image's original dimensions, there's a lot of white space visible next to the image, which does not look nice. It looks even worse when figcaption, which spans the entire width of the widget, is focused.

I think a remedy is `width: 100%` instead of `max-width: 100%` in `.ck-editor__editable .image > img`.

---

**Expected**:

![image](https://cloud.githubusercontent.com/assets/1099479/24544965/9f5f16f0-1605-11e7-975b-50bb6ff4131e.png)

**Actual**:

![image](https://cloud.githubusercontent.com/assets/1099479/24544951/941b4944-1605-11e7-8a46-a02e57f26bb5.png)

**Comment by Reinmar** [comment]
> I think a remedy is width: 100% instead of max-width: 100% in .ck-editor__editable .image > img.

Are you sure that small images should be upscaled? Won't that look bad? And is responsivity really about that?

It came to my mind that vertical images fall into the "small images" category. They make take couple of thousand px high when scaled to a 900px width editor. I'm not sure what the user would actually expect.

**Comment by oleq** [comment]
Truth to tell, it should be up to developers how they handle their images and RWD in the integration. 

So it's a matter how we define default styles (`contents.css`?) and it's somehow related to https://github.com/ckeditor/ckeditor5-ui/issues/176.

**Comment by fredck** [comment]
I also think that upscaling images is a bad idea. In the other hand, the widget itself should not be 100% at that point but fit the size of the image, so it would not look as bad as it does right now.

**Comment by oleq** [comment]
I just realized that it's gonna be quite tricky to have the same result as in v4 (centered widget of the width of an image):
![image](https://cloud.githubusercontent.com/assets/1099479/25131684/f4f0d3f2-2446-11e7-8277-751d5fec79cd.png)

because in v5 `<figure>` has no widget wrapper. 

In v4 the wrapper spans the entire width of the editor, has `text-align: center` and the figure has `display: inline-block`. 

In v5 setting `display: inline-block` on the `<figure>` ends up with an image aligned to the left and there's no way to center it (`margin: 0 auto` doesn't work).

So we must either implement a wrapper, which a nasty thing or come up with some brilliant CSS idea to handle this case.

**Comment by Reinmar** [comment]
I think that Drupal 8 uses the same markup and they used `display:table` AFAIR. However, I'd like to believe that there's some more straightforward, flex or something based solution...

**Comment by oleq** [comment]
(probably) related issue https://github.com/ckeditor/ckeditor5-image/issues/2.

**Comment by oleq** [comment]
On second thought, maybe we should wait and see what developers think about the issue now that we released the alpha. CKEditor should meet the most common use cases and if what we have at this moment is wrong, the community will let us know.

I'm leaving the issue open, though. Maybe @szymonkups will chime in.

**Comment by szymonkups** [comment]
I think that closest to what we want to achieve is to set `display: table;	margin: 0 auto;` on centered image:
![image](https://user-images.githubusercontent.com/2396463/31535985-59f9f12e-affd-11e7-8c8b-f351d44c505a.png)
If we want to use flexbox AFAIK we need to have a container defined, which in our case is editor's editable. Setting it to `display: flex` would add flexbox behavior to all elements in the editable.

**Comment by fredck** [comment]
@szymonkups's screenshot is exactly what we should have here.

Question: why can't we add a wrapper to it? (I kinda predict the answer, but want to hear it out loud :))

**Comment by Reinmar** [comment]
I haven't read the entire topic so I may miss your question, @fredck. But the answer may be here: https://stackoverflow.com/questions/29704019/how-to-floatleft-a-container-with-an-image-having-a-relative-width

The wrapper would need to have all the classes because you can't style stuff correctly when the things are wrapped.

These are problems we had in CKE4 and which we avoided here by not using any wrappers.

**Comment by Reinmar** [comment]
cc @dkonopka @oleq Sounds like done now?

**Comment by dkonopka** [comment]
Yup, we can close it - fixed in https://github.com/ckeditor/ckeditor5/issues/1870.

**Comment by oleq** [comment]
Fixed in https://github.com/ckeditor/ckeditor5-image/pull/297.
